### ISSUE TITLE
Bank Wire Status

### ISSUE THREAD

**Issue by GreyEcologist** [coinbase/gdax-tt#118]
How do you verify the status of a bank wire in GDAX? Is there an API to see the status, or to match a wire # and create a bot for events or change of status? 

If Coinbase can't provide adequate support (or any at all), can a bot be used to bypass waiting for hours to get connected to a representative and wait in limbo for funds that are neither here nor there?

**Comment by CjS77** [comment]
I can't comment on support issues in this forum, unfortunately.
