### ISSUE TITLE
Git Error [Failed to execute] for node-rate-limiter (exit code 128)

### ISSUE THREAD

**Issue by unfurledboredom** [coinbase/gdax-tt#12]
Git returns the following error:

> Failed to execute "git ls-remote –tags –heads git://github.com/jhurliman/node-rate-limiter.git"

One way of solving this is running: 
`git config url."https://".insteadOf git://`

And the second was to change the url in the package.json and yarn.lock from 'git://' to 'https://'

This error is received when running `npm install` or `yarn add` on an Windows PC

**Comment by CjS77** [comment]
Thanks - will be fixed on v0.1.15.; Please keep raising Windows compatibility issues. We don't develop or test on Windows machines, so we rely on you guys to raise these issues (and suggest the fixes!)
