### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by padamshrestha** [coinbase/gdax-tt#120]
==== JS stack trace =========================================

Security context: 0x58f3d3a5749 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [/home/iwf/projects/gdax-tt/node_modules/gdax-trading-toolkit/build/src/lib/BookBuilder.js:238] [bytecode=0x328beefeb8f9 offset=19](this=0x49c3d0822d1 <undefined>,order=0x1146aee8f529 <Object map = 0x6ea66b8a4f9>)
    3: arguments adaptor frame: 3->1
    4: forEach(this=0x1146aee8f509 <JSArray[1]>)
    5: addLevel [/home/iwf/projects/gdax-tt/node_module...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 2: 0x11e1ffc [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 6: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 7: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int, v8::internal::PretenureFlag) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 8: v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
 9: v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add(v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, int*) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
10: v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
11: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
12: v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
13: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/home/iwf/.nvm/versions/node/v9.2.1/bin/node]
14: 0x2a258df042fd
Aborted (core dumped)

**Comment by oatssss** [comment]
Just curious, what were you doing to achieve this error? What are your system specs? Generally speaking, a stack trace is more helpful when paired with contextual information.

**Comment by saamalik** [comment]
Possible fix for problem in #110
