### ISSUE TITLE
Mocha is should not be in runtime dependencies

### ISSUE THREAD

**Issue by jkuchar** [coinbase/gdax-tt#126]
I want to use Jest in my project, however mocha and jest conflicts while there is mocha installed.

gdax-tt should NOT depend on mocha in runtime dependencies.

**Comment by CjS77** [comment]
mocha and @types/mocha have been moved to dev-dependencies. That should sort you out when using GTT as a module. If not, then :man_shrugging: , since it must be packaged as part of the dev tools.

https://stackoverflow.com/questions/43541077/why-does-mocha-need-to-be-in-devdependencies
