### ISSUE TITLE
Yahoo Finance API EOL

### ISSUE THREAD

**Issue by jkirkby91-2** [coinbase/gdax-tt#157]
Yahoo Finance API has been discontinued and is now EOL, so the FX provider in GDAX-TT does not work. the openexchange rates provider does not support switching the base pair on free accounts so there is no working FX Filter for this system.

I will leave this here for anyone else wondering why this is not working.

**Comment by sfkiwi** [comment]
Were you able to find any alternate free service? Fixer.io does let you swap base currency but the data is a day old. If I can find a working currency service I'll probably try and write the FX provider implementation for GTT and contribute.

**Comment by CjS77** [comment]
The best, albeit non-ideal route here is to sign up for the free OpenExchangeRate plan and pass the APP_ID as an envar to your apps. it allows 1000 API calls per month, which is ok for most applications.

**Comment by CjS77** [comment]
I would have thought that USD-XYZ fiat rates would capture 99% of the use cases for `ExchangeRateFilter`. If you need to convert, say BTC-EUR to BTC-GBP, you can approximate it pretty well by dividing EUR-USD by GBP-USD and applying accordingly.

The reason this is a very good approximation is that the arbitrage operators in forex markets are very efficient.
