### ISSUE TITLE
Running scripts from /tutorials

### ISSUE THREAD

**Issue by pzagor2** [coinbase/gdax-tt#17]
I just cloned the project and started playing with the examples from `/tutorials` folder.

The `gtt_tutorials_feed.html` suggest running them with `ts-node src/tutorials/t001_feeds.ts` ( wrong path, it should be without `src/`) the problem is that the GTT import from `gdax-trading-toolkit` is not available and you can't fix this with `npm i gdax-trading-toolkit` because you can't reference dependency of itself. 

Would it make sense to have the import reference the files from build folder? `import * as GTT from '../build/src/index';`

If these tutorials are not meant to run from the root of the project, but more as a showcase if would be good to add a note to the docs.

**Comment by pzagor2** [comment]
I just found out that yarn lets you add self as a dependency. So doing `yarn add gdax-trading-toolkit` and then running `ts-node tutorials/t001_feeds.ts` works great.

**Comment by CjS77** [comment]
TIL 👍

**Comment by CjS77** [comment]
Also, the scripts in the `samples` folder are more dev-oriented and don't import the entire library.
