### ISSUE TITLE
Can't connect to feed with API key

### ISSUE THREAD

**Issue by Ike-Clinton** [coinbase/gdax-tt#19]
I'm trying to run the last tutorial example for authenticating to the API but getting the follow errors when running:

``2017-09-15T04:28:12.084Z - debug: Sending {"type":"subscribe","product_ids":["ETH-USD"],"channels":["ticker","heartbeat"],"signature":"MYSIG","key":"MYKEY","timestamp":"thetimestamp","passphrase":"mypassphrase"} message to WS server
2017-09-15T04:28:12.086Z - debug: Reconnection to ETH-USD successful
2017-09-15T04:29:11.864Z - info: The websocket feed to wss://ws-feed.gdax.com (authenticated) has been closed by an external party. We will reconnect in 5 seconds code=1006, reason=
2017-09-15T04:29:11.864Z - debug: Reconnecting to wss://ws-feed.gdax.com (authenticated) in 5 seconds...

It just keeps looping doing this. I have triple checked that my key, secret, and passphrase are all set correctly. what's the deal? When I leave out my API creds, the example runs just fine.

**Comment by CjS77** [comment]
There have been some changes to the GDAX API recently (last day or so) that might have broken something. I'm travelling this week, but I'll look into this as soon as

**Comment by Ike-Clinton** [comment]
Any updates on this? Having the same issue still.

**Comment by pozderf** [comment]
I got it working when changed '/users/self/' to '/users/self/verify' in src/exchanges/gdax/GDAXFeed.ts:212 (as stated in documentation: https://docs.gdax.com/#subscribe)

**Comment by Ike-Clinton** [comment]
@pozderf I made that change and still the error persists. Were there any other files you had to change?

**Comment by pozderf** [comment]
Well, kind of hacky, but I replaced additionally:

import { GDAXFeed } from "gdax-trading-toolkit/build/src/exchanges";
with
import { FeedFactory } from '../src/factories/gdaxFactories';

and GTT.Factories.GDAX.FeedFactory(logger, products).then((feed: GDAXFeed) => {
with
FeedFactory(logger, products).then((feed: GDAXFeed) => {

**Comment by CjS77** [comment]
I've just gotten back from travels today; I should be able to release an update tomorrow with this fix.

**Comment by CjS77** [comment]
After updating the code to match the API changes, there is definitely an issue with `ts-node` here.
Running the generated js with node produces the expected result. 

#28 Fixes this. If ts-node is not working for you, then the new `run-ts.sh` script will compile and run the javascript, so execute `./run-ts.sh src/samples/gdaxAuthChannel.ts` and it should work as a fallback.

If you use windows, feel free to submit a PR for the relevant cmd script

**Comment by CjS77** [comment]
Fixed in #26
