### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tbenr** [coinbase/gdax-tt#233]
I'm building a bot, after some tests i realize i was in a memory leak situation and started some analysis on my code. After a while i decided to first test the base liveorderbook sample to exclude memory leak was caused by the underlining modules.
I got the same issue.

- i'm running ootb **t002_liveOrderbook.ts** just changed prouct from LTC to BTC to have more activity in the orderbook.
- these are my versions:
![screen shot 2018-05-13 at 23 01 06](https://user-images.githubusercontent.com/15999009/39984800-a9006f4e-575c-11e8-8175-4033654760ae.png)
- this is the commandline i run:
![screen shot 2018-05-13 at 23 01 22](https://user-images.githubusercontent.com/15999009/39984824-bcb68a50-575c-11e8-94c9-edd29c1250ce.png)
- this is a sceenshot while running after some hours:
![screen shot 2018-05-13 at 22 59 34](https://user-images.githubusercontent.com/15999009/39984869-de5b521c-575c-11e8-98b3-b4661211a247.png)
- this is the ramping ram usage from droplet dashboard (clean OS installation, no meaningful programs running apart of gdax-tt):
![screen shot 2018-05-13 at 23 00 02](https://user-images.githubusercontent.com/15999009/39984928-06b811fa-575d-11e8-8a16-5355ba95650e.png)

anyone experiencing similar behaviour? is there something wrong in my setup?
Thanks!

**Comment by vahurtad** [comment]
yeah same thing with LiveOrderBook

**Comment by tbenr** [comment]
Just realize the issue was already discussed here #110

**Comment by vahurtad** [comment]
Will try it soon! Thanks.
