### ISSUE TITLE
auth'd web socket doesn't work

### ISSUE THREAD

**Issue by lukepighetti** [coinbase/gdax-tt#249]
If I auth by adding .env environment vars GDAX web socket for ticker stream with not provide events. If I remove the environment vars everything works as expected.

**Comment by lukepighetti** [comment]
```
GDAX_PASSPHRASE=9s8df9s8dfd
GDAX_KEY=sd76f8s7d8f8s7df87sd8f7sd8f7sd8f8sdf
GDAX_SECRET=8s7df98s7df98s7d9f7sd98f7s9d7f9sd87f9sd8f9sd
```

**Comment by a--hoang** [comment]
@lukepighetti i would not recommend dumping your GDAX/Coinbase keys/secrets on github, please delete - security concern

@fb55 @mihar can one of you invalidate the key please?

**Comment by lukepighetti** [comment]
Those aren't real keys.

**Comment by lukepighetti** [comment]
Also, I just made fresh keys and everything works. I must have made a mistake previously! Closed.
