### ISSUE TITLE
"limit" order on Coinbase executes as market order

### ISSUE THREAD

**Issue by lukepighetti** [coinbase/gdax-tt#250]
It appears that if I place a limit order that sometime overlaps the opposite side of the book it executes as a market order. 

Is there any way to make it fail if it will be accepted as a market order? Limit order only. I don't want to pay taker fees.

**Comment by LikeTheWolf** [comment]
You need to place the order with flag "postOnly" set to true, this ensured the order will be rejected if any part would be executed at market. See the gdax api docs for more info on order messages.
