### ISSUE TITLE
Calculation for 12h and 1d is incorrect in IntervalInMS

### ISSUE THREAD

**Issue by djflux** [coinbase/gdax-tt#259]
The calculation for the `12h` and `1d` intervals in `IntervalInMS` in `src/exchanges/PublicExchangeAPI.ts` uses incorrect values.

Here is the code:

```
IntervalInMS['12h'] = 12 * IntervalInMS['12h'];
IntervalInMS['1d'] = 24 * IntervalInMS['24h'];
```

I believe the correct code should read:

```
IntervalInMS['12h'] = 12 * IntervalInMS['1h'];
IntervalInMS['1d'] = 24 * IntervalInMS['1h'];
```

Going to submit a pull request with a fix.

Thanks again for the great toolkit.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
