### ISSUE TITLE
Calling loadBalances with Poloniex

### ISSUE THREAD

**Issue by jstortz** [coinbase/gdax-tt#26]
Hey team,

I am having an problem performing a lookup of balances on Poloniex. I wondered if anyone could take a look here and offer suggestions.

Here is my code, I tried to make it as SMALL as I could for this example:

```
import * as GTT from 'gdax-trading-toolkit';
import { Balances } from 'gdax-trading-toolkit/build/src/exchanges/AuthenticatedExchangeAPI';

const logger = GTT.utils.ConsoleLoggerFactory({ level: 'info' });
const polo = GTT.Factories.Poloniex.DefaultAPI(logger);

logger.log('info', "key: " + process.env.POLONIEX_KEY);
logger.log('info', "sec: " + process.env.POLONIEX_SECRET);

polo.loadBalances()
    .then( (balances: Balances) => {
        logger.log('info', balances.toString());
    })
    .catch( (err) => {
        logger.log('error', err.message, err);
    });
```

I open a terminal and call this code like this:

```
POLONIEX_KEY="MYKEY" POLONIEX_SECRET="MYSECRET" ts-node src/index.ts
```

Whenever I do this I get back this error:
```
{ error: 'Invalid API key.' }
```

The code DOES print/log out the correct key and secret.

I feel like I'm missing something very specific. Does this code work for any of you?

Thanks!

**Comment by CjS77** [comment]
This should be fixed in 0.1.16

**Comment by jstortz** [comment]
Can you explain the rationale behind closing this? I feel the close is premature.

I would propose closing this AFTER 0.1.16 is released and I verify it actually fixes the issue.

**Comment by CjS77** [comment]
`$ npm info gdax-trading-toolkit`

```
{ name: 'gdax-trading-toolkit',
  description: 'A trading toolkit for building advanced trading bots on the GDAX platform',
  'dist-tags': { latest: '0.1.16' }
```

**Comment by jstortz** [comment]
I have pulled 0.1.16 and confirmed it is working for me locally as well. Thanks!

Additionally I reviewed poloAuthDemo and learned some new tricks from that sample. I appreciate that!
