### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by JamesMcMurran** [coinbase/gdax-tt#27]
Hello,
After installing via npm I get the following error.

~$ ./node_modules/.bin/gdaxConsole  --product BTC-USD -t
/home/NAME/node_modules/gdax-trading-toolkit/build/src/consoles/gdaxConsole.js:96
    let { type, amount, cur, coinbase_id } = program.transfer.split(',');
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by jstortz** [comment]
James,

Worked for me. I'm using 0.1.13. Is that what you're using?

```
$ ./node_modules/.bin/gdaxConsole --product BTC-USD -t
--------------------------------------------------------------------------------
Ticker for BTC-USD on GDAX
Price:    3835.17 | Bid:    3835.16 | Ask:    3835.17 | sequence: 21161770
--------------------------------------------------------------------------------
```

**Comment by JamesMcMurran** [comment]
$ nodejs -v v4.2.6
gdax-trading-toolkit@0.1.14

**Comment by JamesMcMurran** [comment]
I also got some errors in the install. Here is the full output in case that helps.


$ npm i gdax-trading-toolkit
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
loadDep:hawk → resolveWit ▄ ╢█████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
- commander@2.9.0 node_modules/gdax-trading-toolkit/node_modules/commander
- mime-db@1.30.0 node_modules/pushbullet/node_modules/mime-db
- mime-types@2.1.17 node_modules/pushbullet/node_modules/mime-types
/home/NAME
├─┬ gdax@0.4.3  (git://github.com/coinbase/gdax-node.git#cdea38a18b0609aed97b877483444d5ea975cd32)
│ └─┬ request@2.74.0
│   ├─┬ har-validator@2.0.6
│   │ └── is-my-json-valid@2.16.1 
│   ├─┬ http-signature@1.1.1
│   │ ├─┬ jsprim@1.4.1 
│   │ │ ├── assert-plus@1.0.0 
│   │ │ ├── extsprintf@1.3.0 
│   │ │ └─┬ verror@1.10.0 
│   │ │   └── assert-plus@1.0.0 
│   │ └─┬ sshpk@1.13.1
│   │   ├── assert-plus@1.0.0 
│   │   ├─┬ dashdash@1.14.1
│   │   │ └── assert-plus@1.0.0 
│   │   └─┬ getpass@0.1.7
│   │     └── assert-plus@1.0.0 
│   └─┬ mime-types@2.1.17 
│     └── mime-db@1.30.0 
├─┬ gdax-trading-toolkit@0.1.14 
│ ├── commander@2.9.0 
│ ├── limiter@1.1.0  (git://github.com/jhurliman/node-rate-limiter.git#58ce2fda6b5c2bc4ccb81ba3768c5b1bc06c91a5)
│ └─┬ pushbullet@2.0.0
│   └─┬ request@2.82.0
│     └─┬ http-signature@1.2.0
│       └── assert-plus@1.0.0 
└── moment@2.18.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/NAME/package.json'
npm WARN NAME No description
npm WARN NAME No repository field.
npm WARN NAME No README data
npm WARN NAME No license field.

**Comment by jstortz** [comment]
Where did you get 0.1.14, did you build it yourself, I though only 0.1.13 was out so far?

```
$ node -v
v8.4.0
```

I have a higher version of node than you, by a lot.

**Comment by jstortz** [comment]
I also used yarn to install...not npm.

Try setting up a new directory, and use yarn to install and see if you have more luck. Should be pretty easy, you're just trying to run the OOTB console sample right?

**Comment by JamesMcMurran** [comment]
I am thinking that it is my NodeJS as I am getting a warning in the console about it.
wanted: {"node":">=6.0.0"}

**Comment by jstortz** [comment]
Ah, good catch. Can you use something like nvm to quickly swap out to a newer version and confirm? Do you have a hard requirement to use the older version?

**Comment by JamesMcMurran** [comment]
Yep, that's the problem. In case anyone with Ubuntu comes across this go to the nodeJS site and get it from there the Ubuntu repo is outdated. It will auto remove the old version.

$ node -v v6.11.3
$ ./node_modules/.bin/gdaxConsole  --product BTC-USD -t
--------------------------------------------------------------------------------
Ticker for BTC-USD on GDAX
Price:    3885.52 | Bid:    3885.51 | Ask:    3885.52 | sequence: 21162462
--------------------------------------------------------------------------------
