### ISSUE TITLE
My contributions are missing

### ISSUE THREAD

**Issue by Ike-Clinton** [coinbase/gdax-tt#38]
Heh, thought I'd point out that for some reason the contribution I made isn't showing up.
Reference: #https://github.com/coinbase/gdax-tt/pull/21

Not a huge issue obviously.

**Comment by CjS77** [comment]
I think the tut has been updated since then to use template strings. The still code works as intended, no? So your contribution (pointing out and fixing the bug) is still there in spirit, and we thank you for that!
