### ISSUE TITLE
Type imports

### ISSUE THREAD

**Issue by valmassoi** [coinbase/gdax-tt#46]
I'm pretty new to typescript. I haven't figured out how to import the types like `GDAXFeed` without doing `import { GDAXFeed } from "gdax-trading-toolkit/build/src/exchanges"` both Atom (with typescript package) and ts-node say `Cannot find name 'GDAXFeed'.` if I just use `import * as GTT from 'gdax-trading-toolkit'`. Does there need to be a `@types/gdax-trading-toolkit` package?

```For brevity, import statements will be omitted from tutorial source snippets. If you’re using a TypeScript-friendly IDE, type definition imports should be added automatically. If you’re using standard Javascript, the GTT is usually the only import you’ll need.```

**Comment by CjS77** [comment]
Hey @valmassoi 

Have you cloned GTT or using the npm package? Because imports are a bit different depending.
If the latter you can still so 100% Javascript route and use whatever import/require format you're comfortable with.
We've also seen some issues depending on the version of tsc, ts-node & node. I'm currently using
```
ts-node v3.3.0
node v7.10.1
typescript v2.5.2
```

Also  #17 may / may not be helpful.

**Comment by valmassoi** [comment]
@CjS77 I'm using it as a npm package. I think it needs the `@types` published to be used as a package https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by CjS77** [comment]
All the type definitions (`*.d.ts`) are included in the the npm package, so there's no need to publish the types separately. (`@types` is for JS-only packages that don't have type information associated with them).

There are 2 definite issues that I've picked up that might be affecting you:
* A few classes have been accidentally missed in the export sections of the relvant `index.ts` files.  (#59). The workaraound right now is to include the full path to the class
* The type definitions for some dependencies (e.g. ccxt) are not automatically found when using the npm package even though they are there).  A workaround for this right now is to copy the `types` directory from the package to the root folder of your project. At some point we need to publish @types for those, or better yet, get the .d.ts files added to the source projects.

**Comment by CjS77** [comment]
v0.1.22 fixes this issue, so no need to use the workaround anymore
