### ISSUE TITLE
Real-time best bid/ask data

### ISSUE THREAD

**Issue by nunoarruda** [coinbase/gdax-tt#63]
I've created the following script to get the best bid/ask data in real-time:
```
import * as GTT from 'gdax-trading-toolkit';
import { GDAX_WS_FEED, GDAXFeed, GDAXFeedConfig } from 'gdax-trading-toolkit/build/src/exchanges';
import { GDAX_API_URL } from 'gdax-trading-toolkit/build/src/exchanges/gdax/GDAXExchangeAPI';
import { TickerMessage } from 'gdax-trading-toolkit/build/src/core';

const product = 'LTC-EUR';
const logger = GTT.utils.ConsoleLoggerFactory();

const options: GDAXFeedConfig = {
    logger: logger,
    auth: { key: null, secret: null, passphrase: null }, // use public feed
    channels: ['ticker'],
    wsUrl: GDAX_WS_FEED,
    apiUrl: GDAX_API_URL
};

GTT.Factories.GDAX.getSubscribedFeeds(options, [product]).then((feed: GDAXFeed) => {
    GTT.Core.createTickerTrigger(feed, product)
        .setAction((ticker: TickerMessage) => {
            console.log(`Best Bid: ${ticker.bid}`);
            console.log(`Best Ask: ${ticker.ask}`);
        });
});
```
I was expecting to get the best bid/ask data instantly, as soon as there's a new best bid/ask but that's not happening:
<img width="337" alt="screen shot 2017-10-19 at 11 49 15" src="https://user-images.githubusercontent.com/1189149/31850570-f4081b78-b643-11e7-8118-1bbcdc25beaf.png">
Any idea on what could be the issue here?

**Comment by nunoarruda** [comment]
I think this is happening because the ticker channel only provides real-time price updates when a match/trade/tick happens and not when there's a new available best bid/ask. Correct me if I'm wrong.

The REST API `loadTicker` method seems to retrieve the latest best bid/ask, which is what I want, but still is there anyway to achieve this using the websocket feed?

**Comment by zhm** [comment]
I think you need a `LiveOrderbook` to get real-time updates on the spread. Once you have a `LiveOrderbook` you can access the spread inside the `LiveOrderbook.update` event:

```
const bestBid = liveOrderbook.book.highestBid.price;
const bestAsk = liveOrderbook.book.lowestAsk.price;
```

**Comment by CjS77** [comment]
Yup, @nunoarruda and @zhm are correct. The GDAX WS feed only sends ticker updates when a trade is made. 
The LiveOrderbook is the way to go if you want spread updates in-between ticks.

**Comment by nunoarruda** [comment]
Thanks @zhm and @CjS77, that was helpful. I've managed to code exactly what I wanted:
```
import * as GTT from 'gdax-trading-toolkit';
import { GDAXFeed } from 'gdax-trading-toolkit/build/src/exchanges';
import { LiveBookConfig, LiveOrderbook, LevelMessage } from 'gdax-trading-toolkit/build/src/core';

const product = 'LTC-EUR';
const logger = GTT.utils.ConsoleLoggerFactory({ level: 'debug' });
const spread = {
    bestBid: '',
    bestAsk: ''
};

GTT.Factories.GDAX.FeedFactory(logger, [product]).then((feed: GDAXFeed) => {
    const config: LiveBookConfig = {
        product: product,
        logger: logger
    };

    const liveorderbook = new LiveOrderbook(config);

    liveorderbook.on('LiveOrderbook.update', (msg: LevelMessage) => {
        const highestBid = liveorderbook.book.highestBid.price.toFixed(2);
        const lowestAsk = liveorderbook.book.lowestAsk.price.toFixed(2);

        if (highestBid.valueOf() !== spread.bestBid.valueOf()) {
            spread.bestBid = highestBid;
            console.log(`New best bid: ${spread.bestBid}`);
        }

        if (lowestAsk.valueOf() !== spread.bestAsk.valueOf()) {
            spread.bestAsk = lowestAsk;
            console.log(`New best ask: ${spread.bestAsk}`);
        }
    });

    feed.pipe(liveorderbook);
});
```

**Comment by CjS77** [comment]
@nunoarruda Glad to help.

If you think spread is a useful metric, how about submitting a PR to add it to the LiveOrderbook class?

**Comment by nunoarruda** [comment]
@CjS77 not sure what functionality I would add.
