### ISSUE TITLE
Graceful shutdown of WebSocket feed

### ISSUE THREAD

**Issue by zhm** [coinbase/gdax-tt#64]
Version: `0.1.19`

Currently calling `feed.disconnect()` mostly works, except it leaves the `connectionChecker` interval alive. This causes the node process to hang indefinitely when trying to shutdown the feed.

[This](https://github.com/coinbase/gdax-tt/blob/9dd3b5783e9c528f99b84a82a907cbbb13ee948c/src/exchanges/ExchangeFeed.ts#L144) looks like the place where we need to `clearInterval()`.

Somewhere in the `disconnect()` / `close()` path I think just needs a:

```js
clearInterval(this.connectionChecker);
```

I added this in my own code for now and it does indeed let it gracefully exit.

**Comment by CjS77** [comment]
Good catch. I had fixed this somewhere in one of my dev branches, so should make it into a release soon.
