### ISSUE TITLE
Is there a way to get my current holding positions?

### ISSUE THREAD

**Issue by tianyangj** [coinbase/gdax-tt#74]
This is definitely a question rather than issue, not sure where is the best place to ask.

What is the best way to find out my current positions, like cash, BTC, ETH etc. As I am making trades, when trade get partially filled or cancelled, I'd like to get a subscription of my latest holding positions.

**Comment by CjS77** [comment]
I believe [loadOrders](https://coinbase.github.io/gdax-tt/apiref/interfaces/_src_exchanges_authenticatedexchangeapi_.authenticatedexchangeapi.html#loadallorders) is what you're looking for

**Comment by tianyangj** [comment]
Thanks for reply, this is an awesome project. 

Yes, you are right, I can use loadAllOrders and loadBalances to get my current positions. However, I need to "pull" for them. What I am really looking for is my current positions get "pushed" to me, like I can subscribe to some kind of stream, so I can get up to date positions. The closest thing I can find is Trader.trade-executed, but I need to manually keep track of my remaining positions if my order get partially filled.

**Comment by CjS77** [comment]
Right so I don't think the GTT has a nice object to do _exactly_ what you want right now, but I may have some suggestions on how to get there.

Firstly, `Trader`: It does keep track of its order portfolio, but exactly and only that: *its* order portfolio. This means that if `Trader` didn't explicitly place an order, it ignores any messages related to trades, even if its on the same API key. This allows you to have multiple Traders doing different things without them interfering. 

So `Trader` might be what you want, as long as all orders are placed with 'PlaceOrderMessage` messages.

You can also look at the raw `GDAXFeed` stream. Make sure you subscribe to the `user` channel when connecting (with your API keys), and you'll be able to watch for the following messages:

```
export interface TradeExecutedMessage extends StreamMessage 
export interface TradeFinalizedMessage extends StreamMessage
export interface MyOrderPlacedMessage extends StreamMessage
```

You can peek at the `Trader` for ideas on how to aggregate this into a portfolio watcher

You'l' still need to 'pull' from the API though to get an initial view of your positions. And the GDAX ws api doesn't provide updates on balances, so you'll need to poll for that.

**Comment by tianyangj** [comment]
Great, thanks for the suggestions.
