### ISSUE TITLE
Real Time Data 

### ISSUE THREAD

**Issue by hhussaini** [coinbase/gdax-tt#81]
book.on('LiveOrderbook.update', () => {
         console.log(printOrderbook(book, 5));
         printOrderbookStats(book);
         checkBook(book); //my own method which does a bunch of comparisons and sets up a trade
    });

Currently I'm using the live order book set up from t002_liveOrderbook.ts. I added the above code into the feed and deleted the code in the snapshot section. This works for a few minutes but then i get this error:

error: A websocket connection to GDAX was established, but
 product subscription failed. reason=Socket is not connected. Have you called connect
()? Otherwise the connection may have dropped and is in the process of reconnecting.

After reconnecting it will start printing again except it will be a few second behind, printing old information. I can't figure out how to consistently get real time data. Any help would be appreciated

**Comment by CjS77** [comment]
It sounds like the issue is with the network or server. Are you still experiencing these issues?

Some other things to check
- Have you tried connecting to an auth feed using API keys? Does that improve things?
- Are you hitting any other (REST) endpoints at the same time?

**Comment by hhussaini** [comment]
Yes actually i'm already using the auth feed and API keys. Not hitting any other REST endpoints that i know of as long as that tutorial doesn't because it is a copy of the LiveOrderbook tutorial except the changes i made. 

The LiveOrderbook is working fine for you for long periods of time? Does it have to do with the fact that i took out the setInterval() code? Because without the setInterval(), and with the above code, it does update practically instantly. The only problem is this error that drops the connection

**Comment by hhussaini** [comment]
Found the issue. For some reason, the feed.reconnect(0) in the skipped message section was causing problems the entire time. Took that out and liveorderbook is updating beautifully and programs working great, thanks.
