### ISSUE TITLE
loadAllOrders() returns 0.0 for the price on pending limit orders

### ISSUE THREAD

**Issue by rmm5t** [coinbase/gdax-tt#83]
**Steps to Recreate:**

Option 1:

1. Run `gdaxAPI.loadAllOrders()` on an account with pending limit orders
2. Inspect the results

Option 2:

1. Run `gdaxConsole -O` on an account with pending limit orders
2. Note the price column.

**What I expected:**

I expected the returned objects to contain a value or both `size` and `price` corresponding to the pending limit order

**What I experienced:**

Only the `size` contained a valid `BigNumber` value. `price` always seems to be `Big(0.0)`.

However, `extra.size` and `extra.price` seem to contain the correct values albeit as strings.

 ---

**`gdax-trading-toolkit` version `0.1.29`**

**Comment by CjS77** [comment]
Time to start raising that test coverage 😊
